# Generated by Django 3.1.3 on 2022-07-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20220717_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=15, unique=True)),
                ('market_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('discount', models.IntegerField()),
                ('our_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.CharField(choices=[('ORDER_PLACED', 'Order_Placed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='ORDER_PLACED', max_length=15)),
                ('order_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('market_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('our_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('qty', models.IntegerField()),
                ('units', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
