# Generated by Django 4.0.1 on 2022-08-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
