# Generated by Django 4.0.1 on 2022-06-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=15, unique=True)),
                ('product_name', models.CharField(max_length=15)),
                ('product_description', models.TextField()),
                ('market_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('discount', models.IntegerField()),
                ('our_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
