# Generated by Django 4.0.1 on 2022-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_selling',
            field=models.BooleanField(default=False),
        ),
    ]
