# Generated by Django 4.0.1 on 2022-02-08 19:47

import authapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', authapp.models.BaseUserManager()),
            ],
        ),
    ]
